CREATE TABLE notes (
	id INTEGER PRIMARY KEY,
	type TEXT NOT NULL,
	title TEXT NOT NULL,
	url TEXT NOT NULL,
	image TEXT NOT NULL,
	content TEXT NOT NULL,
	entities TEXT NOT NULL,
	color TEXT NOT NULL,
	group_id INTEGER,
	user_id INTEGER,
	timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (group_id) REFERENCES groups(id),
	FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE groups (
	id INTEGER PRIMARY KEY,
	user_id INTEGER,
	FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE users (
	id INTEGER PRIMARY KEY,
	email TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL
);